name: Build Plugin

on: [push]

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node 
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 20
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Uploads plugin artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: animate-block-on-scroll
          path: |
            animate-block-on-scroll.php
            LICENSE
            readme.txt
            build
            assets
